let data;
export default data = {
	init: {
		userID: "primary id of user in database",
		userStatus: "status of user",
		avatar: "user/default image",
		fname: "user's first name",
		lname: "user's last name",
		phone: "phone number of user",
	},
	get_header_info: {
		avatar: "user profile image (null/empty String if its not uploaded)",
		status: "user status",
		name: "user's first name",
	},
	personal_data_tab: {
		fname: "علیرضا",
		lname: "رحمانی",
		nationalCode: "94463123",
		phone: "09222222222",
		address: "تهران - خیابان دوم - پلاک 3",
		avatar: "",
		city: "تهران",
		neighborhood: "باغ فیض",
		houseNumber: "15",
		unitNumber: "16",
		gender: "مرد",
		maritalStatus: "مجرد",
		score: "باتجربه",
	},
	personal_document_tab: {
		birthDoc: "birth certificate photo (first page)",
		nationalDoc: "national card photo",
		backgroundDoc: "bad background document photo",
		homeDoc: "home document photo",
	},
	finantial_tab_basic_info: { income: "9600000", credit: "3300000" },
	finantial_tab_transactions_table: [
		{
			type: "درآمد",
			value: "900000",
			date: "1400/5/1",
			paycode: "sdfsafgaerg",
		},
		{
			type: "درآمد",
			value: "1300000",
			date: "1400/5/2",
			paycode: "gareftgt",
		},
		{
			type: "برداشت",
			value: "200000",
			date: "1400/5/3",
			paycode: "vtrgdfget",
		},
	],
	finantial_tab_bank_account_table: [
		{
			accountNumber: "9595 3123 5846 2111",
			bank: "تجارت",
			owner: "علیرضا رحمانی",
			shaba: "20546421684518",
		},
		{
			accountNumber: "4671 3023 5546 2841",
			bank: "سامان",
			owner: "علیرضا رحمانی",
			shaba: "34567890987645",
		},
		{
			accountNumber: "4671 7686 5546 2841",
			bank: "'گردشگری'",
			owner: "علی بیک دولتی",
			shaba: "34852895257645",
		},
	],
	works_todo: [
		{
			service: "ضدعفونی",
			area: "100",
			disinfection: "وایتکس",
			locationType: "",
			haspet: "دارد",
			date: "1400/4/4",
			workTime: "12 - 14 ",
			amount: "1,200,000",
			orderCode: "1 ",
			address: "تهران - باغ فیض - پلاک 6 واحد 8",
		},
		{
			service: "نظافت",
			area: "120",
			disinfection: "",
			locationType: "مسکونی",
			haspet: "ندارد",
			date: "1400/5/5",
			workTime: "15 - 17",
			amount: "8,600,000",
			orderCode: "2 ",
			address: "مشهد - خیابان امام رضا - پلاک 22 - واحد 8",
		},
	],
	works_done: [
		{
			service: "ضدعفونی",
			area: "100",
			disinfection: "وایتکس",
			locationType: "",
			haspet: "دارد",
			date: "1400/4/4",
			workTime: "12 - 14 ",
			amount: "1,200,000",
			orderCode: "1 ",
			address: "تهران - باغ فیض - پلاک 6 واحد 8",
		},
		{
			service: "نظافت",
			area: "120",
			disinfection: "",
			locationType: "مسکونی",
			haspet: "ندارد",
			date: "1400/5/5",
			workTime: "15 - 17",
			amount: "8,600,000",
			orderCode: "2 ",
			address: "مشهد - خیابان امام رضا - پلاک 22 - واحد 8",
		},
	],
	work_condition_tab: {
		works: {
			cleaningHouse: true,
			disinfectionPlaces: true,
			jointsCleaning: false,
			washingDishes: true,
			wallWashing: false,
		},
		isPetFriendly: false,
		startTime: 12,
		endTime: 16,
	},
};
